services:
  - type: web
    name: quickpharm
    env: docker
    dockerfilePath: Dockerfile
    region: oregon
    plan: starter
    autoDeploy: true
    envVars:
      - key: ROOT_URL
        value: https://quickpharm.onrender.com
      - key: PORT
        value: "3000"
      - key: METEOR_ALLOW_SUPERUSER
        value: "1"
      - key: MONGO_URL
        sync: false
      - key: MAIL_URL
        sync: false
